version: '3'
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeos
    container_name: nodeosapp
    environment: {}
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./app:/app
    command: npm start
